### PR TITLE
Just keep the port upon restart

### LINKED ISSUE #65: tt should try to keep the same port on restart
Otherwise, any in-flight test will fail.
It's really not hard to do, we just need to keep the port instead of wiping the entire config...

### PR DESCRIPTION
**Pull request by Babar**
Do not throw the baby with the bath water when shutting down.

closes #65

### CODE REVIEW

File: lib/taste_tester/config.rb [hunk 1]
```diff
@@ -95,8 +95,13 @@ def self.relative_databag_dir
...
 
     def self.chef_port
+      require 'taste_tester/state'
+      previous_ports = []
+      if TasteTester::State.port
+        previous_ports << TasteTester::State.port
+      end
       range = chef_port_range.first.to_i..chef_port_range.last.to_i
-      range.to_a.shuffle.each do |port|
+      (previous_ports + range.to_a.shuffle).each do |port|
```
Comment (jaymzh) [inline lib/taste_tester/config.rb]: it took me a minute to figure out why you made that an array. FWIW, I woulda done it this way:

```
range = (chef_port_range.first.to_i..chef_port_range.last.to_i).to_a
if TasteTester::State.port
  range.prepend(TasteTester::State.port)
end
range.shuffle.each do |port|
```

**Comment by jaymzh** [comment]
Not waiting for tests since it's just space changes and the tests passed last time.

**Comment by jaymzh** [comment]
Thanks @Babar !!
